name: speedo_flutter
description: A Flutter plugin for real-time internet speed tracking (Mbps) using native platform streams.
version: 1.0.0
homepage: https://github.com/shaan1997/speedo_flutter
repository: https://github.com/shaan1997/speedo_flutter

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.speedo_flutter
        pluginClass: SpeedoFlutterPlugin
      ios:
        pluginClass: SpeedoFlutterPlugin
